version: '2.1'

services:
  lint:
    command: bash -c "luacheck -q ."
    build:
      context: .
    volumes:
      - ".:/lua/"
    working_dir: "/lua"

  test:
    command: ./resty_busted -c --shuffle
    build:
      context: .
    volumes:
      - ".:/lua/"
    working_dir: "/lua"
