version: '2.1'

services:
  base:
    build:
      context: .
    volumes:
      - ".:/lua/"
    working_dir: "/lua"

  lint:
    command: bash -c "luacheck -q ."
    extends:
      service: base

  test:
    command: ./resty_busted -c --shuffle
    extends:
      service: base

  prove_test:
    command: bash -c "prove -r t"
    extends:
      service: base

  doc:
    command: ldoc -f markdown src -d docs
    extends:
      service: base
