version: '2.1'

services:
  app:
    build:
      context: .
    volumes:
      - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./src/:/lua/src/"
    ports:
      - "5050:5050"
      - "6060:6060"
      - "7070:7070"
    links:
      - admin
    depends_on:
      - admin

  admin:
    build: ./admin
    command: bash -c "./scripts/wait-for.sh db 3306 && rails db:migrate && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./admin:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=admin

  db:
    image:  mariadb:10.9.4
    volumes:
      - "./mysqldata:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=admin
      - MYSQL_TCP_PORT=3306
