version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=admin
  web:
    build: .
    command: bash -c "./scripts/wait-for.sh db 3306 && rails db:migrate:reset && rake db:seed && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=admin
