name: CI - Lua Lint and Busted (Lua Tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag lua-resty-dynacode:$(date +%s)
    - name: Lint
      run: docker run --rm -v $(pwd):/lua -w /lua lua-resty-dynacode:$(date +%s) bash -c "./resty_busted -c --shuffle"
