name: CI - Lua Lint and Busted (Lua Tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: |
        docker build . --file Dockerfile --tag lua-resty-dynacode:${{ github.sha }}
        docker run --rm -v $(pwd):/lua -w /lua lua-resty-dynacode:${{ github.sha }} bash -c "luacheck -q ."
    - name: Tests
      run: |
        docker build . --file Dockerfile --tag lua-resty-dynacode:${{ github.sha }}
        docker run --rm -v $(pwd):/lua -w /lua lua-resty-dynacode:${{ github.sha }} bash -c "./resty_busted -c --shuffle"
